### ISSUE TITLE
Any plans on working with the Kanban board feature?

### ISSUE THREAD

**Issue by jleseane23** [Hoffelhas/automation-todoist#1]
It's not make or break for me, but I noticed when switching to the Kanban board view it drops the next_action tag

**Comment by Hoffelhas** [comment]
Hi there. I haven't had a look at the new kanban board yet, so I'd have to see how it functions first and if anything has changed with the API. If it is a bug I can do something about I'll for sure try fix it.

**Comment by Hoffelhas** [comment]
Hi. Now that Kanban boards has been released it seems that tags do show up properly. If sub-tasks are tagged however it's not immediately visible, but that's unfortunately a feature of how the boards overview works. This also moves into the realm of the work-flow of Autodoist and Kanban - or rather the difference - but that's a whole other topic to think about.

For now I will close this, but if you have any additional remarks feel free to contact me.
