### ISSUE TITLE
Hide Future flag ignored is due time is set

### ISSUE THREAD

**Issue by moorsey** [Hoffelhas/automation-todoist#10]
If a due time is set on a task, then "-hf" is ignored.

Take the time off and the "next" label is added back, add a time back for the same day and the label is re-added

**Comment by Hoffelhas** [comment]
Hi there, sorry it took a while. Had to take some time off due to personal reasons.

Time in a due date could indeed not be processed. I've created a fix for this, which has been pushed to the dev branch. This bugfix will be part of the next master release!

**Comment by moorsey** [comment]
No problem at all, this is great news, thanks for looking into it!
