### ISSUE TITLE
!* doens't work

### ISSUE THREAD

**Issue by guidoknoop** [Hoffelhas/automation-todoist#14]
The !* command doesn't work because Todoist turns an exclamation mark in an underscore.

**Comment by bas1425** [comment]
@Hoffelhas First and foremost, thank you so much for creating Autodist. Best thing to ever happen to Todoist!! 

@Hoffelhas I am experiencing the same issue. What should we do to get this fixed? Many thanks! 

@guidoknoop Have you found any solutions in the meantime?

**Comment by Hoffelhas** [comment]
Hi there. I've just now tried to replicate this, but the exclamation mark doesn't seem to turn into an underscore. Hence, it seems to still work. Could you please verify it that's indeed the case, or if you guys still experience this problem?

**Comment by Hoffelhas** [comment]
Ah ok I was able to recreate the issue. For sections it indeed turns the '!' into a '_', while this doesn't seem to happen in tasks. I'll work on a fix for this.

**Comment by bas1425** [comment]
You are awesome :).

**Comment by Hoffelhas** [comment]
So, I've pushed a hotfix to the dev-branch. For now the underscore will be simply be detected and the logic should work again.

When I've finished a bunch of open bugfixes and requests, this'll be a part of a new version I'll put on the master branch too!

If you have any more questions, don't hesitate to reach out. For now I'll close the topic.
