### ISSUE TITLE
`next_action` labels in board view

### ISSUE THREAD

**Issue by jhereth** [Hoffelhas/automation-todoist#19]
Hi,

when using a board, sections are turned into columns. Working on an item will move it to the next column without necessarily finishing it. Iiuc autodoist marks the first item in the list (leftmost column) as `next_item`. This leads to me having many `next_item` labels in this project.

Would it be possible to 

1) remove that label if the task is not topmost in the column (first section)?
2) and maybe not have it at all in the rightmost column (usually done)?

If there is no plan to support the board view, please let me know (I like the board view but if I have to chose I'll prefer autodoist :) )

**Comment by obbardc** [comment]
maybe fixed with https://github.com/Hoffelhas/autodoist/pull/21

**Comment by obbardc** [comment]
also #22 fixes an interesting case when the "next" card has bee ignored due to being in the future ;-)

**Comment by Hoffelhas** [comment]
Hi there, sorry it took a while to get back at you.

Something like this is possible in v2.0.0 that will be released soon. You could do either of two things:

- Specify that a section should be labelled sequentially by using '-'  in each section name, except for the last 'done' section. 
- If you have many sections, you could simply specify '=-' in the project name, such that all sections in parallel are labelled sequentially each. Labelling for the 'done' section can then be ignored by using '*' either at the start or end of its name.

If you have any more questions, feel free to reopen this thread. For now I will close it.
