### ISSUE TITLE
Section support?

### ISSUE THREAD

**Issue by nickwg03** [Hoffelhas/automation-todoist#2]
Is there a way to add suffixes to the section head and get the same behavior of tasks within that section?

For example: 
![image](https://user-images.githubusercontent.com/4528512/97723356-4ed39000-1a91-11eb-947f-7ac6629cafee.png)

Maybe the sections aren't exposed in the API?

**Comment by Hoffelhas** [comment]
Hi there,

Thanks for reaching out with this suggestion. I've had others approach me with a similar request, since this feature would be quite useful in combination with Boards.

Hence, know that this feature is planned to be added in the next update. There's no clear date for that yet, but it's something I want to release this month at least.

**Comment by Hoffelhas** [comment]
Well November didn't work out, haha. Nevertheless, I have started the work to implement it, so for now I can only ask for your patience.

**Comment by nickwg03** [comment]
> Well November didn't work out, haha. Nevertheless, I have started the work to implement it, so for now I can only ask for your patience.

Sounds great, thanks!

**Comment by Hoffelhas** [comment]
Hi there, quick update on the section support. I've gone a bit all out and refactored the main workings of the code, but now the section support has been included in a much cleaner way, code-wise, than the first idea I had. 

Next up is cleaning up the code and internal testing before it's released.

**Comment by Hoffelhas** [comment]
Section labelling has been included in v1.4 that has just been released! For now I'll close this topic, but if there are any more issues feel free to open a new one.

**Comment by nickwg03** [comment]
Awesome, thanks!
