### ISSUE TITLE
Todoist-python deprecated

### ISSUE THREAD

**Issue by ensjens** [Hoffelhas/automation-todoist#23]
According to their github page https://github.com/Doist/todoist-python, todoist-python is now deprecated.

They recommend using todoist-api-python instead https://github.com/Doist/todoist-api-python.

**Comment by ShayHill** [comment]
I fear this may be the reason autodoist has stopped working. Wish I had time to fork it. Too many todos!!

**Comment by machielkreiken** [comment]
It stopped for so many users in that case. I hope someone will fix it. Sadly i'm not Python guy :(

**Comment by ShayHill** [comment]
My workflow really depends on this, so I’ve written a new version that only does sequential and parallel task labeling. I am testing today and will upload to GitHub this evening. Maybe that will help some of us.

Sent from my iPhone

On Dec 12, 2022, at 02:08, Machiel ***@***.***> wrote:

﻿

It stopped for so many users in that case. I hope someone will fix it. Sadly i'm not Python guy :(

**Comment by ShayHill** [comment]
> It stopped for so many users in that case. I hope someone will fix it. Sadly i'm not Python guy :(

[https://github.com/ShayHill/todoist_bot](https://github.com/ShayHill/todoist_bot)

I am "a Python guy" but this is alpha software after a few hours of coding and two days of testing. Seems to work, and the bones are good. I have my automations back.

**Comment by RoccoMathijn** [comment]
This deprecated library made use of the sync endpoint v8 which has been removed since Nov 30. https://developer.todoist.com/sync/v8#overview

I'm wondering how hard it would be to switch this project to the todoist-api-python library. Can try to have a crack at it this weekend

**Comment by RoccoMathijn** [comment]
I think I have the next action functionality working. Next up: regenerate subtasks and postpone end of day. Progress here https://github.com/RoccoMathijn/autodoist/tree/update-todoist-lib

**Comment by RoccoMathijn** [comment]
Regeneration of subtasks is now main functionality! I'll remove that part completely
https://todoist.com/help/articles/whats-new#finish-the-year-strong-dec-15

**Comment by JoergBr** [comment]
> Regeneration of subtasks is now main functionality! I'll remove that part completely https://todoist.com/help/articles/whats-new#finish-the-year-strong-dec-15

That's great, thank you for the info!

**Comment by Hoffelhas** [comment]
Hi there! Thanks for your help, it's really great to see others reach out and assist with this.  We also had a short discussion in #28 regarding this, but I'm also still ongoing with the code-change which I'm planning finish as soon as possible.

Regarding the regeneration: earlier last year Todoist asked users to provide feedback for new future integrations that they could work on. Autodoist features were also mentioned, and thanks to the support of many of you regeneration was seen as useful enough to be integrated as core functionality in Todoist itself! It's indeed a feature that can be depreciated from Autodoist at this point.

**Comment by Hoffelhas** [comment]
Closing this topic for now, updates will be mentioned in #28.
