### ISSUE TITLE
Sequential Processing not adjusting to changes properly

### ISSUE THREAD

**Issue by erauner12** [Hoffelhas/automation-todoist#27]
https://www.loom.com/share/6b5e879a62d040498b8b4737450dfa0e

In this workflow, using sequential processing. I would expect whatever is at the top of a default list to have next action tag and everything below it to be removed.

But it seems that when the order is manually adjusted, that whatever was on top does not get the `next_action` tag removed. The tag stays, whether it is on a top level task or a subtask level.

**Comment by Hoffelhas** [comment]
Hi there, thanks for letting me know about this bug. Currently I'm working on a big overhaul of Autodoist; in the latest dev version I've implemented a fix for this, so I'm closing this thread for now. If similar issues are still experienced in the future, feel free to reopen this.
