### ISSUE TITLE
Task text for NOT regenerating sub-tasks in recurring lists

### ISSUE THREAD

**Issue by JoergBr** [Hoffelhas/automation-todoist#5]
I love the autodoist functionality, especially regenerating sub-tasks in recurring lists and making multiple items uncheckable / re-checkable at the same time.

Sometimes I need a certain task NOT to regenerate sub-tasks in recurring lists. Would it be possible to introduce a special prefix / suffix / text inside the task name that tells autodoist to skip this task in the regeneration process?

**Comment by Hoffelhas** [comment]
Hi there, thanks for your support! 

To get a better idea of this type of workflow, could you give me more information on the following?

Is it the idea that such a task will be unchecked by you on a later time? Or should the task in essence be deleted?

Could you also give an example of such a task and sub-tasks?

**Comment by JoergBr** [comment]
Thank you for your feedback!

I will start with the example: I have a daily recurring task "Follow up on past meetings". I mark it as completed when I have followed up on all the meetings of today. Sometimes I have other priorities and I can only follow up on some meetings, but not all. Then I create sub-tasks with the names of the meetings I could not follow up on today. I mark the recurring task as completed and the next day it will reoccur with these subtasks, reminding me that I have to follow up not only on today's meetings but also on that certain meetings from yesterday. Once I complete the follow up on those, I complete the respective subtasks. And then when I complete the main task lateron, I don't want all the past meetings to reappear as subtasks, of course.

Sure I could handle this in other ways, e.g not making the meeting follow-up a subtask of that recurring task, but actually I like it this way because it holds the meetings to follow up in one task context.

So instead of handling all the recurring tasks either in the way Autodoist does (with the -r flag) or in the usual Todoist way, I think it would be great if you could determine the behaviour individually in the main task using a specific prefix, text or suffix.

Does that make sense to you?

**Comment by JoergBr** [comment]
Actually I'd have one further request, and since it is also regarding the functionality of the recurring tasks I will add it here:

I also have recurring tasks where I complete one subtask every time and the next subtask the next time the main task occurs. A possible description for the main task would be "Complete one household task" and then the subtasks would be for example "clean living room", "clean kitchen" etc. So if the main task is a daily task, I complete one subtask every day and complete the main task every day.

In this case, the subtasks should only be regenerated when they are all complete so that the todos start over from the beginning. This would be different from the current autodoist behaviour because a subtask should not be regenerated every time I complete the main task, but only when all the subtasks are complete.

Maybe it would be possible to implement this behaviour AND the behaviour above (todoist standard behaviour) as two different switches (in the form of certain main task prefixes / texts / suffixes).

This would be definitely worth a bigger "coffee" spending from my side. ;-)

**Comment by Hoffelhas** [comment]
Thanks for the additional explanation, I see what you mean. The current regeneration functionality is still 'everything or nothing', so I like your suggestion to have more control over where it happens and what should happen.

Looking at your example we now have three modes of interest. 1) Todoist vanilla (your first example), 2) main task completion regenerates everything (Autodoist now), and 3) main task completion regenerates only if there are no sub-tasks left (your second example).

Thinking about the implementation it would perhaps be easiest to still allow an '-r' type flag in order to enable mode 2 or 3 en masse, while allowing manually assigned labels to individual tasks in order to use mode 1, 2 or 3. (come to think of, using labels would have been nicer with the start-date functionality too... ah well).

Just need to build the foundation to easily use the label for this functionality, but overall this isn't too hard to pull off (ha - famous last words). I'll keep you updated.

**Comment by Hoffelhas** [comment]
Quick update: I've implemented what was described above. Tomorrow I'll run a few tests and push it to the dev branch, so you have the possibility to play with it first.

**Comment by Hoffelhas** [comment]
Hi, you can check out the dev branch now if you want. You can run autodoist with the -r tag and specify which overall functionality you want to enable, e.g. "-r 1" enables regeneration of all sub-tasks for all recurring top items. Check out --help for all the modes.

In addition you'll notice a few 'Regen" labels will automatically be added to your Todoist. These can manually be assigned to top recurring items to specify the functionality at that place.

Please let me know how it works and what your thought are.

**Comment by JoergBr** [comment]
Wow, thank you for the quick implementation! Your summary about the three types and the implementation via arguments and/or labels sounds really great and would be exactly what I need.

I have cloned the dev branch and tried it, but actually I could not get anything other than the standard todoist functionality to work. Maybe I did something wrong... I started the program with the -r flag (and also with -r 1 just to make sure, which should result in the same behavior as I understood from the --help), the three Regen labels were immediately created (that tells me that I managed to use the dev branch ;-), but when I created recurring test tasks with subtasks and completed them, none of the subtasks were regenerated - no matter if I used one of the labels (Regen_all / Regen_all_if_completed) in the main task or not, and even when I completed all of the subtasks.

I also started the program with --debug and I found the information "New recurring task detected" for the task I created, but I didn't find more information that I'd consider helpful in the issue.

Could it be that there's a catch that I missed somewhere, or maybe a bug in the dev branch? Let me know if there's anything I can test or provide you with.

**Comment by Hoffelhas** [comment]
Hi, I'll give it another look and perhaps put in more relevant debug messages. I'll let you know when you can try it out again!

**Comment by Hoffelhas** [comment]
Yup, that was a bug. That's what happens if you fix stuff at night without drinking coffee.

In any case, it seems to run better now. I've also added more relevant debug logging, and removed the overflow of redundant ones for more clarity. Please let me know what your experience is.

**Comment by JoergBr** [comment]
Works like a charm - thank you so much! This will make my todoist usage even more productive. Coffee is on its way... ;-)

**Comment by Hoffelhas** [comment]
I'm glad your happy! Thanks a lot for your suggestions and support!
