### ISSUE TITLE
Auto tag tasks with sub tasks

### ISSUE THREAD

**Issue by moorsey** [Hoffelhas/automation-todoist#7]
Just a thought / suggestion, along GTD lines I think

I have thought it might be useful to auto tag all indent 1 tasks that have sub tasks with "@project" or similar (Todoist doesn't allow the use of "project" as a label)

This would allow a review of such tasks, to check they all have a next action

This could perhaps be extended to check for "tasks with closed sub tasks and no open ones" and label differently, for example

That is one filter in Todoist I have found lacking, it has no "knowledge" of "tasks with tasks", no idea if the API allows this

Cheers

**Comment by Hoffelhas** [comment]
Hi, since this request has been made a while ago: is this still something that you would like to see, or has anything changed in this regard?

**Comment by moorsey** [comment]
My GTD is all a bit of the mess right now to be honest, I have found myself manually scanning through projects in Todoist, checking the "(4/5)" sub task indicator, to see if any have all sub tasks checked off and then closing, or adding another next action as required.

So manual workaround, not sure if this would be the solution, will close for now and think on it for future!

Thanks
